name: frontend
description: "ECO WRAP - AI Based Intelligent Food Packaging Recommendation System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/eco_wrap_logo.png"
  adaptive_icon_background: "#F7FBF8"
  adaptive_icon_foreground: "assets/images/eco_wrap_logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/splash/